# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
    inputs:
      connection_number:
        description: 'Number of connections'
        default: '10'
      connection_string:
        default: 'user=test dbname=test password=test sslmode=disable'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install PostgreSQL and PostGIS
      uses: nyaruka/postgis-action@v2.1.0
      with:
        postgresql db: test
        postgresql user: test
        postgresql password: test

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Test
      run: go test -v ./...
